(* DO NOT EDIT THIS FILE: automatically generated by ../configure *)
(* Exact command that generated this file: *)
(* ./configure.ml -local -native-compiler no -debug -annotate *)

let local = true
let vmbyteflags = ["-dllib";"-lcoqrun";"-dllpath";"/home/egallego/external/coq-git/kernel/byterun";]
let coqlib = None
let configdir = Some "/home/egallego/external/coq-git/ide"
let datadir = Some "/home/egallego/external/coq-git/ide"
let docdir = ""
let ocaml = "/home/egallego/.opam/4.03.0/bin//ocaml"
let ocamlfind = "/home/egallego/.opam/4.03.0/bin/ocamlfind"
let ocamllex = "/home/egallego/.opam/4.03.0/bin//ocamllex"
let camlbin = "/home/egallego/.opam/4.03.0/bin/"
let camllib = "/home/egallego/.opam/4.03.0/lib/ocaml"
let camlp4 = "camlp5"
let camlp4o = "/home/egallego/.opam/4.03.0/bin/camlp5o"
let camlp4bin = "/home/egallego/.opam/4.03.0/bin"
let camlp4lib = "/home/egallego/.opam/4.03.0/lib/camlp5"
let camlp4compat = "-loc loc"
let cflags = "-Wall -Wno-unused -g -O2"
let best = "opt"
let osdeplibs = "-cclib -lunix"
let version = "trunk"
let caml_version = "4.03.0"
let date = "June 2016"
let compile_date = "Jun 7 2016 16:34:32"
let arch = "Linux"
let arch_is_win32 = false
let exec_extension = ""
let coqideincl = "-I \"/home/egallego/.opam/4.03.0/lib/lablgtk2\""
let has_coqide = "opt"
let gtk_platform = `X11
let has_natdynlink = true
let natdynlinkflag = "true"
let vo_magic_number = 8511
let state_magic_number = 58511
let with_geoproof = ref false
let browser = "firefox -remote \"OpenURL(%s,new-tab)\" || firefox %s &"
let wwwcoq = "http://coq.inria.fr/"
let wwwrefman = "http://coq.inria.fr/distrib/trunk/refman/"
let wwwstdlib = "http://coq.inria.fr/distrib/trunk/stdlib/"
let localwwwrefman = "file://html/refman"
let no_native_compiler = true

let plugins_dirs = [
  "plugins/btauto";
  "plugins/cc";
  "plugins/decl_mode";
  "plugins/derive";
  "plugins/extraction";
  "plugins/firstorder";
  "plugins/fourier";
  "plugins/funind";
  "plugins/micromega";
  "plugins/nsatz";
  "plugins/omega";
  "plugins/quote";
  "plugins/romega";
  "plugins/rtauto";
  "plugins/setoid_ring";
  "plugins/syntax";
  "plugins/xml";
]
